# Generated by Django 4.2 on 2023-10-10 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_autobus',
            fields=[
                ('id_autobus', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='model_horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('hora_pico', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='model_programacion_cargadores',
            fields=[
                ('id_programacion_cargadores', models.AutoField(primary_key=True, serialize=False)),
                ('autobus_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model_autobus')),
                ('horario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model_horario')),
            ],
        ),
        migrations.CreateModel(
            name='model_programacion_autobuses',
            fields=[
                ('id_programacion_autobuses', models.AutoField(primary_key=True, serialize=False)),
                ('autobus_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model_autobus')),
                ('horario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model_horario')),
            ],
        ),
        migrations.CreateModel(
            name='model_cargador',
            fields=[
                ('id_cargador', models.AutoField(primary_key=True, serialize=False)),
                ('autobus_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model_autobus')),
            ],
        ),
    ]
